dataset:
  source : ###
  path : ###
  currencies : ###
  start_period : ###
  end_period : ###

hyperparams:
  learning_rate : 0.005
  comission_rate : 0.0025
  mini_batch : 50
  beta : 5e-5
  train_start : 1000
  train_freq : 100

inputs:
  feature_number : 3
  window_size : 50
  coin_number : 11
  start_date : "2019/07/01"
  end_date : "2022/07/01"

