dataset:
  source : 'CSV'
  path : 'data/'
  currencies : ['BTC', 'ETH', 'ETC', 'BNB', 'XRP']
  start_period : "2019/07/01"
  end_period : "2022/07/01"

hyperparams:
  learning_rate : 0.02
  comission_rate : 0.0025
  mini_batch : 100
  beta : 0.05
  train_start : 1000
  train_freq : 500

inputs:
  feature_number : 3
  window_size : 50
  coin_number : 11
  init_value : 1000

